import type { SourceRecord } from "../types";

/**
 * AIJUR source library.
 *
 * Every record is `reference_only` unless AIJUR owns it. The library tells us
 * *which* competencies exist and *what good practice looks like*. No phrasing,
 * exercise, table or figure from any of these works is reproduced anywhere in
 * the content set.
 */
export const SOURCES: SourceRecord[] = [
  {
    id: "src.managing-professional-service-firm",
    title: "Managing the Professional Service Firm",
    author: "David H. Maister",
    year: 1993,
    language: "en",
    publisher: "Free Press",
    domains: [
      "dom.client-relations",
      "dom.firm-operations",
      "dom.business-development",
      "dom.teamwork-leadership",
    ],
    sections: [
      "Part One: Basic Matters — A Question of Balance; The Professional Firm Life Cycle; Profitability: Health and Hygiene; Solving the Underdelegation Problem",
      "Part Two: Client Matters — The Practice Development Package; Listening to Clients; Quality Work Doesn't Mean Quality Service; A Service Quality Program; Marketing to Existing Clients; How Clients Choose; Attracting New Clients; Managing the Marketing Effort",
      "Part Three: People Matters — How's Your Asset?; How to Build Human Capital; The Motivation Crisis; On the Importance of Scheduling; On the Meaning of Partnership; Surviving the People Crisis",
      "Part Four: Management Matters — How Practice Leaders Add Value; How to Create a Strategy; Fast-Track Strategy",
      "Part Five: Partnership Matters — Partner Performance Counseling; The Art of Partner Compensation; Patterns in Partner Compensation; Pie-Splitting; Partnership Governance",
      "Part Six: Multisite Matters — The One-Firm Firm; Hunters and Farmers; Making the Network Work; Creating the Collaborative Firm; Coordinating Industry Specialty Groups",
      "Part Seven: Final Thoughts — Asset Management",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The backbone of AIJUR's separation between technical quality and perceived service quality: a client judges the relationship, not the legal analysis. We took from it the case for systematic client listening, expectation and perception management, and the argument that under-delegation is a firm-level competency failure rather than a personal habit.",
    kind: "operations",
  },
  {
    id: "src.client-centered-law-firm",
    title: "The Client-Centered Law Firm",
    author: "Jack Newton",
    year: 2020,
    language: "en",
    publisher: "Blue Check Publishing",
    domains: ["dom.client-relations", "dom.firm-operations", "dom.digital-ai"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Held in the library as the reference work on designing the whole client journey — intake, responsiveness, transparency and follow-up — as a deliberate service rather than a by-product of legal work. Available only as a PDF that has not yet been ingested, so no competency extraction has been performed against it.",
    kind: "professional",
  },
  {
    id: "src.game-changing-attorney",
    title: "The Game Changing Attorney",
    author: "Michael Mogill",
    year: 2018,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: ["dom.business-development", "dom.communication", "dom.client-relations"],
    sections: [
      "A David and Goliath Story",
      "Lawyering Ain't What It Used to Be",
      "The Best Cases Go to the Best Marketers",
      "Become the Obvious Choice",
      "Tell Your Story",
      "From Story to Value Proposition",
      "Go Small to Go Big",
      "The New Buyer's Journey",
      "The Case for Video Marketing",
      "Getting the Most Out of Your Video",
      "Marketing 101",
      "How Do You Measure Success?",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Source of AIJUR's position that a lawyer must be able to state, in one sentence a non-lawyer understands, why a client should choose them. We drew the idea of a defined client journey with distinct stages, and the discipline of measuring business development instead of assuming it works.",
    kind: "professional",
  },
  {
    id: "src.selling-the-invisible",
    title: "Selling the Invisible: A Field Guide to Modern Marketing",
    author: "Harry Beckwith",
    year: 1997,
    language: "en",
    publisher: "Warner Books",
    domains: ["dom.business-development", "dom.client-relations", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library for one reason: a client cannot inspect legal work before buying it, so they buy signals — clarity, responsiveness, confidence, follow-through. Still a PDF awaiting ingestion, so it has not yet been mined for competency statements.",
    kind: "professional",
  },
  {
    id: "src.smarter-collaboration",
    title: "Smarter Collaboration: A New Approach to Breaking Down Barriers and Transforming Work",
    author: "Heidi K. Gardner and Ivan Matviak",
    year: 2022,
    language: "en",
    publisher: "Harvard Business Review Press",
    domains: ["dom.teamwork-leadership", "dom.business-development", "dom.firm-operations"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Reserved as the evidence base for why cross-practice work produces better client outcomes and stickier relationships than the lone-expert model that still dominates much of the regional market. Not yet ingested — the copy in the library is a PDF.",
    kind: "professional",
  },
  {
    id: "src.lawyers-ceo",
    title: "The Lawyer as CEO",
    author: "Reza Torkzadeh",
    year: 2022,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: [
      "dom.firm-operations",
      "dom.teamwork-leadership",
      "dom.client-relations",
      "dom.digital-ai",
    ],
    sections: [
      "Part I: It Starts with You — A Small Firm in a Big World; Becoming a CEO",
      "Part II: Building Your Culture — Find Your Why; An Office of True Believers; Culture Tech",
      "Part III: Connecting to Your Client — Meeting the Modern Customer's Expectations; Client Tech",
      "Part IV: You Are the Firm — Advertise Authentically; Taking Care of the CEO; Moving Beyond You",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Gave AIJUR the framing that today's client compares the firm to every other service they use, not only to other law firms — which raises the bar on response times and updates. We also took its treatment of delegation as the precondition for a practice that survives its founder.",
    kind: "operations",
  },
  {
    id: "src.be-the-ceo",
    title: "Be the CEO of Your Law Firm: Gain Control, Turn a Profit, and Reclaim Your Life",
    author: "Alexandra Lozano",
    year: 2018,
    language: "en",
    publisher: "Ramses House Publishing",
    domains: [
      "dom.firm-operations",
      "dom.business-development",
      "dom.client-relations",
      "dom.self-management",
    ],
    sections: [
      "Creating Your Vision and Strategy (role of Chief Executive Officer)",
      "Marketing Your Services (role of Chief Marketing Officer)",
      "Taming Your Finances (role of Chief Financial Officer)",
      "Managing Your Firm (role of Chief Operating Officer)",
      "Cultivating Your Relationships (roles of Chief Public Relations Officer and Chief Sales Officer)",
      "Attaining Client Satisfaction (role of Chief Communications Officer)",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The role-based split of a practice — strategy, marketing, finance, operations, relationships, client communication — informed how AIJUR divides its firm-operations and business-development domains. Its treatment of the consultation as a tracked, converted event shaped our matter-intake skill.",
    kind: "operations",
  },
  {
    id: "src.small-firm-roadmap",
    title: "The Small Firm Roadmap Revisited: A Guide to the Healthy Law Firm of Your Future",
    author: "Stephanie Everett and Aaron Street",
    year: 2023,
    language: "en",
    publisher: "Lawyerist Media",
    domains: [
      "dom.firm-operations",
      "dom.client-relations",
      "dom.teamwork-leadership",
      "dom.self-management",
    ],
    sections: [
      "Part 1: How We Got Here — Lawyers Are Falling Behind; A Look Toward the Future; Rethinking Law as a Business; The Lawyerist Vision",
      "Part 2: The Small Firm Roadmap — Preparing for the Journey; Healthy Strategy; Healthy Team; Healthy Clients; Healthy Systems; Healthy Profits; Healthy Owners",
      "The Future of Law Is Yours",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Directly behind AIJUR's insistence that unanswered calls, unexplained delays and impenetrable drafting are the real client complaints — not lost cases. Its healthy-systems material shaped our workflow, file-organisation and quality-control skills.",
    kind: "operations",
  },
  {
    id: "src.modernize-your-law-firm",
    title: "Modernize Your Law Firm: Transform Your Law Firm for the Future",
    author: "Lynda Artesani",
    year: 2024,
    language: "en",
    publisher: "Business Expert Press",
    domains: ["dom.digital-ai", "dom.firm-operations"],
    sections: [
      "History of Law Firm Workflows",
      "Understanding the Automation Process",
      "Why Outdated Software Is Hurting Your Firm",
      "Data Security",
      "The Virtual Firm",
      "Identify Your Tech Stack",
      "Adjustments to Make in a Post-COVID World",
      "How to Adapt and Get Your Staff to Accept Technology",
      "Microsoft or Google?",
      "The Future: Legal Accounting and Blockchain",
      "Summary and Final Comments: Recommendations for a Modern Law Firm",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The practical basis for AIJUR's digital and AI domain: map the workflow before automating it, treat client data security as a professional obligation, and expect resistance from the team as a normal stage rather than a failure.",
    kind: "operations",
  },
  {
    id: "src.legal-ops-kpis",
    title: "Legal Operations KPIs: The Professional's Handbook to Operational Excellence",
    author: "Mori Kabiri",
    year: 2024,
    language: "en",
    publisher: "InfiniGlobe",
    domains: ["dom.firm-operations", "dom.professional-judgment", "dom.digital-ai"],
    sections: [
      "Part I: Definitions — From Data to Strategic Insights; data, metric, indicator, KRI, RI, KPI, PI and report; Legal Data Analytics Readiness Model; why and how we visualise data",
      "Part II: List of Metrics and Reports — Spend Management; Budgeting; matter, vendor, practice-area and cycle-time measures",
      "Part III: Best Practices",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Taught AIJUR the difference between a number a firm collects and a number a firm acts on. We used its logic — cycle time, budget variance, matter ageing — to define what measurable evidence a lawyer can offer for the quality-control and workflow skills.",
    kind: "operations",
  },
  {
    id: "src.fire-proof",
    title:
      "Fireproof: A Five-Step Model to Take Your Law Firm from Unpredictable to Wildly Profitable",
    author: "Mike Morse and John Nachazel",
    year: 2021,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.business-development"],
    sections: [
      "Know Thyself",
      "Hiring, Firing, and Paying",
      "The Jumbotron Principle",
      "Run Your Business like You Run Your Biggest Case",
      "Cherry Garcia Beats Vanilla",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Source of AIJUR's view that a firm should apply to its own operations the rigour it applies to a major case file. Its scoreboard idea and its documented, repeatable intake procedure shaped our matter-intake and quality-control levels.",
    kind: "operations",
  },
  {
    id: "src.68-power-moves",
    title: "68 Power Moves to Build a Law Firm Clients Can't Ignore",
    author: "Neal Goldstein",
    year: 2024,
    language: "en",
    publisher: "Advantage Media",
    domains: ["dom.client-relations", "dom.business-development", "dom.self-management"],
    sections: [
      "Laying the Foundation — Establishing Genuine Connections",
      "Storytelling and Communication — Building Bonds Through Words",
      "Nurturing Relationships — Family, Friends, and the Community",
      "Mastering Your Time — Daily, Weekly, and Yearly Habits",
      "Investing in Personal Growth — Soft Skills and Mentorship",
      "The Power of Relationships — Building and Strengthening Networks",
      "Client-Centered Approach — Treating Clients Like Family",
      "Going Beyond — Unexpected Ways to Build Relationships",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "A catalogue of small, repeatable relationship behaviours — calling the client before they call you, naming the weaknesses of a case honestly, reviewing the calendar on a fixed rhythm. AIJUR took the principle that trust is built by many small kept promises, not one impressive performance.",
    kind: "professional",
  },
  {
    id: "src.four-thousand-weeks",
    title: "Four Thousand Weeks: Time Management for Mortals",
    author: "Oliver Burkeman",
    year: 2021,
    language: "en",
    publisher: "Farrar, Straus and Giroux",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "Part I: Choosing to Choose — The Limit-Embracing Life; The Efficiency Trap; Facing Finitude; Becoming a Better Procrastinator; The Watermelon Problem; The Intimate Interrupter",
      "Part II: Beyond Control — We Never Really Have Time; You Are Here; Rediscovering Rest; The Impatience Spiral; Staying on the Bus; The Loneliness of the Digital Nomad; Cosmic Insignificance Therapy; The Human Disease",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Underpins AIJUR's refusal to teach time management as fitting more in. We took the argument that capacity is fixed, so priority setting is an act of deliberate refusal, and that chasing total efficiency simply raises the volume of incoming work.",
    kind: "professional",
  },
  {
    id: "src.meditations-for-mortals",
    title:
      "Meditations for Mortals: Four Weeks to Embrace Your Limitations and Make Time for What Counts",
    author: "Oliver Burkeman",
    year: 2024,
    language: "en",
    publisher: "Farrar, Straus and Giroux",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "Week One: Being Finite — on the liberation of defeat; on actually doing things; on paying the price; against productivity debt; the art of reading and not reading; you can't care about everything; let the future be the future",
      "Week Two: Taking Action — decision-hunting; finish things; look for the life task; befriending what you fear; rules that serve life; three hours; develop a taste for problems",
      "Week Three: Letting Go — what if this were easy?; the reverse golden rule; don't stand in generosity's way",
      "Week Four: Showing Up",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Gave AIJUR the practice of finishing matters rather than accumulating open ones, and the done-list idea behind our reflection steps. It supports the resilience skill's stance that a lawyer never reaches a trouble-free phase and should stop waiting for one.",
    kind: "professional",
  },
  {
    id: "src.your-brain-at-work",
    title:
      "Your Brain at Work: Strategies for Overcoming Distraction, Regaining Focus, and Working Smarter All Day Long",
    author: "David Rock",
    year: 2020,
    language: "en",
    publisher: "Harper Business",
    domains: [
      "dom.self-management",
      "dom.teamwork-leadership",
      "dom.negotiation-influence",
      "dom.professional-judgment",
    ],
    sections: [
      "Act I: Problems and Decisions — The Morning Information Overwhelm; A Project That Hurts to Think About; Juggling Five Things at Once; Saying No to Distractions; Searching for the Zone of Peak Performance; Getting Past a Roadblock",
      "Act II: Stay Cool Under Pressure — Derailed by Drama; Drowning amid Uncertainty; When Expectations Get Out of Control",
      "Act III: Collaborate with Others — Turning Enemies into Friends; When Everything Seems Unfair; The Battle for Status",
      "Act IV: Facilitate Change — When Other People Lose the Plot; The Culture That Needs to Transform",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The cognitive science behind several AIJUR design rules: decide hard questions while fresh, name an emotion to reduce its grip, and treat status, certainty and fairness as live threats in any negotiation or feedback conversation. It also grounds our warning that unmanaged client expectations become emotional events, not information gaps.",
    kind: "professional",
  },
  {
    id: "src.the-antidote",
    title: "The Antidote: Happiness for People Who Can't Stand Positive Thinking",
    author: "Oliver Burkeman",
    year: 2012,
    language: "en",
    publisher: "Faber and Faber",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "On Trying Too Hard to Be Happy",
      "What Would Seneca Do? The Stoic Art of Confronting the Worst-Case Scenario",
      "The Storm Before the Calm: A Buddhist Guide to Not Thinking Positively",
      "Goal Crazy: When Trying to Control the Future Doesn't Work",
      "Who's There? How to Get Over Your Self",
      "The Safety Catch: The Hidden Benefits of Insecurity",
      "The Museum of Failure: The Case for Embracing Your Errors",
      "Memento Mori: Death as a Way of Life",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Supports AIJUR's hardest professional rule: never promise an outcome. Naming the realistic worst case out loud calms a client more than reassurance does, and treating errors as reviewable material rather than shame is the basis of our quality-control and resilience skills.",
    kind: "professional",
  },
  {
    id: "src.introverted-leader",
    title: "The Introverted Leader: Building on Your Quiet Strength",
    author: "Jennifer B. Kahnweiler",
    year: 2018,
    language: "en",
    publisher: "Berrett-Koehler Publishers",
    domains: ["dom.teamwork-leadership", "dom.communication", "dom.business-development"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "In the library so that AIJUR's leadership and presentation skills do not assume an extroverted personality — preparation and listening are treated as leadership assets, not compensations. The copy available is a PDF that has not been ingested.",
    kind: "professional",
  },
  {
    id: "src.rainmaker",
    title: "How to Become a Rainmaker: The Rules for Getting and Keeping Customers and Clients",
    author: "Jeffrey J. Fox",
    year: 2000,
    language: "en",
    publisher: "Hyperion",
    domains: ["dom.business-development", "dom.client-relations", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Retained as a short, blunt reference on client acquisition discipline: prepare before the meeting, ask about the client's problem before describing your service, and follow up exactly when you said you would. PDF only, not yet ingested.",
    kind: "professional",
  },
  {
    id: "src.they-ask-you-answer",
    title: "They Ask, You Answer",
    author: "Marcus Sheridan",
    year: 2019,
    language: "en",
    publisher: "Wiley",
    domains: ["dom.business-development", "dom.communication", "dom.client-relations"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Held for its core proposition that answering the questions clients are embarrassed to ask — especially about cost and risk — is the most effective form of professional marketing. Awaiting ingestion; the library copy is a PDF.",
    kind: "professional",
  },
  {
    id: "src.built-to-sell",
    title: "Built to Sell: Creating a Business That Can Thrive Without You",
    author: "John Warrillow",
    year: 2011,
    language: "en",
    publisher: "Portfolio",
    domains: ["dom.firm-operations", "dom.business-development", "dom.teamwork-leadership"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Kept as the reference for building a practice whose value sits in its documented process rather than in one lawyer's memory — the commercial argument behind AIJUR's knowledge-management and delegation skills. Not yet ingested; PDF only.",
    kind: "operations",
  },
  {
    id: "src.purple-cow",
    title: "Purple Cow: Transform Your Business by Being Remarkable",
    author: "Seth Godin",
    year: 2003,
    language: "en",
    publisher: "Portfolio",
    domains: ["dom.business-development", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "In the library as the counterweight to interchangeable professional positioning: if a client cannot tell two firms apart, price decides. It will be referenced for commercial awareness and business development once ingested; currently a PDF.",
    kind: "professional",
  },
  {
    id: "src.jab-jab-right-hook",
    title: "Jab, Jab, Jab, Right Hook: How to Tell Your Story in a Noisy Social World",
    author: "Gary Vaynerchuk",
    year: 2013,
    language: "en",
    publisher: "HarperBusiness",
    domains: ["dom.business-development", "dom.communication", "dom.digital-ai"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Held for the sequencing principle behind professional visibility online: give useful content repeatedly before asking for anything, and adapt the message to each platform rather than reposting it. Still a PDF, so no extraction has been run.",
    kind: "professional",
  },
  {
    id: "src.legal-project-management",
    title:
      "Legal Project Management: Control Costs, Meet Schedules, Manage Risks, and Maintain Sanity",
    author: "Steven B. Levy",
    year: 2009,
    language: "en",
    publisher: "Day Pack Books",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.client-relations"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "The library's dedicated reference for scoping a matter, agreeing deliverables and dates with the client, and re-planning openly when the facts change. It will anchor the workflow and expectation-management skills; the copy is a PDF awaiting ingestion.",
    kind: "operations",
  },
  {
    id: "src.governance-raci",
    title: "Governance & RACI Framework — دليل تحديد الأدوار والمسؤوليات",
    author: "AIJUR",
    year: 2025,
    language: "ar",
    publisher: "AIJUR Legal Operations & Governance System",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.professional-judgment"],
    sections: [
      "الهدف (Purpose)",
      "تعريف RACI",
      "المبادئ الأساسية — مسؤول معتمد واحد فقط لكل عملية",
      "RACI للعمليات الأساسية: إدارة القضايا، اتخاذ القرار القانوني، الإدارة اليومية",
      "هيكل الحوكمة: المستوى الاستراتيجي، المستوى التشغيلي، المستوى الإداري",
      "ربط RACI مع النظام (AIJUR Integration)",
      "آلية التطبيق",
      "قواعد إلزامية",
      "النتيجة المتوقعة",
      "الاعتماد",
    ],
    usageRights: "owned",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "AIJUR's own governance document and the only Arabic-first source in the library. It supplies the rule our delegation and teamwork skills are built on: every matter and every decision has exactly one accountable owner recorded in the system, with responsibility, consultation and information assigned separately.",
    kind: "framework",
  },
  {
    id: "src.how-to-argue-and-win",
    title: "How to Argue and Win Every Time",
    author: "Gerry Spence",
    year: 1995,
    language: "en",
    publisher: "St. Martin's Press",
    domains: ["dom.negotiation-influence", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Kept for its argument that credibility and plain speech persuade further than technique, and that listening is the opening move of any argument. Held as a PDF; no competency extraction has been performed yet.",
    kind: "advocacy",
  },
  {
    id: "src.making-your-case",
    title: "Making Your Case: The Art of Persuading Judges",
    author: "Antonin Scalia and Bryan A. Garner",
    year: 2008,
    language: "en",
    publisher: "Thomson/West",
    domains: ["dom.negotiation-influence", "dom.communication", "dom.legal-english"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "The library's standard on disciplined legal writing and oral argument — lead with the strongest point, concede what must be conceded, never overstate an authority. Reserved for the presentation and plain-explanation skills; PDF only.",
    kind: "advocacy",
  },
  {
    id: "src.tools-of-argument",
    title: "The Tools of Argument: How the Best Lawyers Think, Argue, and Win",
    author: "Joel P. Trachtman",
    year: 2013,
    language: "en",
    publisher: "CreateSpace",
    domains: ["dom.negotiation-influence", "dom.professional-judgment"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Held as a compact map of the recurring moves in legal argument — burden, interpretation, procedure, evidence — useful for teaching a junior lawyer to anticipate the other side. Awaiting ingestion as a PDF.",
    kind: "advocacy",
  },
  {
    id: "src.thinking-like-a-lawyer",
    title: "Thinking Like a Lawyer: A New Introduction to Legal Reasoning",
    author: "Frederick Schauer",
    year: 2009,
    language: "en",
    publisher: "Harvard University Press",
    domains: ["dom.professional-judgment", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "In the library as the theoretical account of rule-following, analogy and precedent that explains why lawyers reason differently from their clients — which is precisely why plain explanation has to be trained. PDF, not yet ingested.",
    kind: "advocacy",
  },
  {
    id: "src.legal-analyst",
    title: "The Legal Analyst: A Toolkit for Thinking about the Law",
    author: "Ward Farnsworth",
    year: 2007,
    language: "en",
    publisher: "University of Chicago Press",
    domains: ["dom.professional-judgment", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Reserved for the decision-making skill: incentives, risk allocation and the cost of being wrong are the tools a lawyer needs when advising rather than litigating. Held as a PDF pending ingestion.",
    kind: "advocacy",
  },
  {
    id: "src.maccarthy-cross-exam",
    title: "MacCarthy on Cross-Examination",
    author: "Terence F. MacCarthy",
    year: 2007,
    language: "en",
    publisher: "American Bar Association",
    domains: ["dom.negotiation-influence", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "Kept for its discipline on question design — short, single-fact, controlled questions — which AIJUR inverts for client interviewing, where the aim is to open rather than to close. PDF awaiting ingestion.",
    kind: "advocacy",
  },
  {
    id: "src.rule-of-law",
    title: "The Rule of Law",
    author: "Tom Bingham",
    year: 2010,
    language: "en",
    publisher: "Allen Lane",
    domains: ["dom.professional-judgment"],
    usageRights: "reference_only",
    analysisStatus: "pending",
    reviewStatus: "ai_suggested",
    notes:
      "The library's anchor for professional ethics: law that is accessible, equality before it, and the lawyer's duty to the system as well as to the client. It will support the ethics skill's higher levels; currently a PDF that has not been ingested.",
    kind: "professional",
  },
  {
    id: "src.ultimate-associate-marketing",
    title: "The Ultimate Law Firm Associate's Marketing Checklist",
    author: "Ross Fishman",
    year: 2019,
    language: "en",
    publisher: "Fishman Marketing",
    domains: ["dom.business-development", "dom.self-management"],
    sections: [
      "Introduction — why associates avoid business development",
      "A year-by-year checklist from first-year to senior associate",
      "Internal visibility and relationships inside the firm",
      "Writing, speaking and article placement",
      "Social media and professional networks",
      "Building and maintaining a contact list",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Confirmed for AIJUR that business development is a staged competency with different expectations at each year of practice, not a partner-only activity. Its year-by-year structure informed how our business-development and relationship-building levels rise.",
    kind: "professional",
  },
  {
    id: "src.ali-rise",
    title: "All Rise: Practical Tools for Building High-Performance Legal Teams",
    author: "Benjamin Sachs",
    year: 2024,
    language: "en",
    publisher: "American Bar Association",
    domains: [
      "dom.teamwork-leadership",
      "dom.self-management",
      "dom.communication",
      "dom.firm-operations",
    ],
    sections: [
      "Part 1: Trust — Psychological Safety; The Fundamental Attribution Error; Working Style Differences; Trust Building Without Trust Falls",
      "Part 2: Ownership — The Broken Venn Diagram; Managing Up; Managing Down; Cultivating Ownership",
      "Part 3: Productive Conflict — Iron Sharpens Iron; Conflict Styles; Emotional Obstacles; Breaking Stalemates",
      "Part 4: Accountability — Going Supersonic; Project Management; Autonomy; Creating a Culture of Continuous Feedback; Evaluating High-Performance Legal Teams",
      "Appendices: Team Building Program Template; Team Health Assessment Survey Template",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The richest single source for AIJUR's teamwork and leadership domain: psychological safety as the precondition for a junior raising a problem early, managing up as a named skill, and feedback as a continuous habit rather than an annual event. Its project-management and autonomy material shaped our delegation levels.",
    kind: "professional",
  },
];
