import type { SourceRecord } from "../types";

/**
 * AIJUR source library.
 *
 * Every record is `reference_only` unless AIJUR owns it. The library tells us
 * *which* competencies exist and *what good practice looks like*. No phrasing,
 * exercise, table or figure from any of these works is reproduced anywhere in
 * the content set.
 */
export const SOURCES: SourceRecord[] = [
  {
    id: "src.managing-professional-service-firm",
    title: "Managing the Professional Service Firm",
    author: "David H. Maister",
    year: 1993,
    language: "en",
    publisher: "Free Press",
    domains: [
      "dom.client-relations",
      "dom.firm-operations",
      "dom.business-development",
      "dom.teamwork-leadership",
    ],
    sections: [
      "Part One: Basic Matters — A Question of Balance; The Professional Firm Life Cycle; Profitability: Health and Hygiene; Solving the Underdelegation Problem",
      "Part Two: Client Matters — The Practice Development Package; Listening to Clients; Quality Work Doesn't Mean Quality Service; A Service Quality Program; Marketing to Existing Clients; How Clients Choose; Attracting New Clients; Managing the Marketing Effort",
      "Part Three: People Matters — How's Your Asset?; How to Build Human Capital; The Motivation Crisis; On the Importance of Scheduling; On the Meaning of Partnership; Surviving the People Crisis",
      "Part Four: Management Matters — How Practice Leaders Add Value; How to Create a Strategy; Fast-Track Strategy",
      "Part Five: Partnership Matters — Partner Performance Counseling; The Art of Partner Compensation; Patterns in Partner Compensation; Pie-Splitting; Partnership Governance",
      "Part Six: Multisite Matters — The One-Firm Firm; Hunters and Farmers; Making the Network Work; Creating the Collaborative Firm; Coordinating Industry Specialty Groups",
      "Part Seven: Final Thoughts — Asset Management",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The backbone of AIJUR's separation between technical quality and perceived service quality: a client judges the relationship, not the legal analysis. We took from it the case for systematic client listening, expectation and perception management, and the argument that under-delegation is a firm-level competency failure rather than a personal habit.",
    kind: "operations",
  },
  {
    id: "src.client-centered-law-firm",
    title: "The Client-Centered Law Firm",
    author: "Jack Newton",
    year: 2020,
    language: "en",
    publisher: "Blue Check Publishing",
    domains: ["dom.client-relations", "dom.firm-operations", "dom.digital-ai"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read in substantial part — introduction, the chapters on expectation-setting, client-first versus client-centered decision-making, empathy, and measuring success, plus the conclusion. Its contribution is treating client experience as inseparable from the legal product itself, and then operationalizing that claim: evidence that reducing client effort predicts loyalty more reliably than delighting clients; a bidirectional decision test that checks every firm change against both client impact and internal efficiency; a diagnostic habit of asking why clients generate repeat contact before redesigning a touchpoint; and a discipline of closing feedback loops with NPS/CES/CSAT rather than anecdote. We took from it a sharper, effort-based framing of expectation management, a metrics literacy for client experience largely absent elsewhere in the library, and billing transparency as a deliberate trust-building technique.",
    kind: "professional",
  },
  {
    id: "src.game-changing-attorney",
    title: "The Game Changing Attorney",
    author: "Michael Mogill",
    year: 2018,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: ["dom.business-development", "dom.communication", "dom.client-relations"],
    sections: [
      "A David and Goliath Story",
      "Lawyering Ain't What It Used to Be",
      "The Best Cases Go to the Best Marketers",
      "Become the Obvious Choice",
      "Tell Your Story",
      "From Story to Value Proposition",
      "Go Small to Go Big",
      "The New Buyer's Journey",
      "The Case for Video Marketing",
      "Getting the Most Out of Your Video",
      "Marketing 101",
      "How Do You Measure Success?",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Source of AIJUR's position that a lawyer must be able to state, in one sentence a non-lawyer understands, why a client should choose them. We drew the idea of a defined client journey with distinct stages, and the discipline of measuring business development instead of assuming it works.",
    kind: "professional",
  },
  {
    id: "src.selling-the-invisible",
    title: "Selling the Invisible: A Field Guide to Modern Marketing",
    author: "Harry Beckwith",
    year: 1997,
    language: "en",
    publisher: "Warner Books",
    domains: ["dom.business-development", "dom.client-relations", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Beckwith's core argument is that a service does not exist until it is performed, so clients buy the invisible on the strength of visible proxies — promptness, tone, small kept promises — and judge satisfaction as the gap between what they expected and what they got, not against any absolute standard. We took from it the case that perceived quality must be actively managed rather than assumed to speak for itself: audit every point of client contact, calibrate promises so as not to manufacture disappointment, and proactively resurface progress and wins during a matter, since unlike a product, good legal work leaves nothing behind to remind the client it happened.",
    kind: "professional",
  },
  {
    id: "src.smarter-collaboration",
    title: "Smarter Collaboration: A New Approach to Breaking Down Barriers and Transforming Work",
    author: "Heidi K. Gardner and Ivan Matviak",
    year: 2022,
    language: "en",
    publisher: "Harvard Business Review Press",
    domains: ["dom.teamwork-leadership", "dom.business-development", "dom.firm-operations"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The evidence base for treating cross-practice, cross-silo collaboration as a measurable driver of revenue, retention, and resilience rather than a soft cultural aspiration. We took from it: the reframe that cross-selling is vendor-focused while true collaboration is client-focused, backed by data on the revenue multiplier of multi-service client relationships; an explicit taxonomy of collaboration-enabling skills (influence without authority, conflict management, comfort with ambiguity); the finding that new or lateral hires have roughly six months to build reciprocal trust before disengaging; the case that direct pay-for-collaboration backfires while collective scorecards work; the \"tokenism\" and \"Mini-Me\" traps showing diverse team composition doesn't guarantee equitable access to high-value work; and \"threat rigidity\", the pattern by which pressure degrades group decision quality.",
    kind: "professional",
  },
  {
    id: "src.lawyers-ceo",
    title: "The Lawyer as CEO",
    author: "Reza Torkzadeh",
    year: 2022,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: [
      "dom.firm-operations",
      "dom.teamwork-leadership",
      "dom.client-relations",
      "dom.digital-ai",
    ],
    sections: [
      "Part I: It Starts with You — A Small Firm in a Big World; Becoming a CEO",
      "Part II: Building Your Culture — Find Your Why; An Office of True Believers; Culture Tech",
      "Part III: Connecting to Your Client — Meeting the Modern Customer's Expectations; Client Tech",
      "Part IV: You Are the Firm — Advertise Authentically; Taking Care of the CEO; Moving Beyond You",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Gave AIJUR the framing that today's client compares the firm to every other service they use, not only to other law firms — which raises the bar on response times and updates. We also took its treatment of delegation as the precondition for a practice that survives its founder.",
    kind: "operations",
  },
  {
    id: "src.be-the-ceo",
    title: "Be the CEO of Your Law Firm: Gain Control, Turn a Profit, and Reclaim Your Life",
    author: "Alexandra Lozano",
    year: 2018,
    language: "en",
    publisher: "Ramses House Publishing",
    domains: [
      "dom.firm-operations",
      "dom.business-development",
      "dom.client-relations",
      "dom.self-management",
    ],
    sections: [
      "Creating Your Vision and Strategy (role of Chief Executive Officer)",
      "Marketing Your Services (role of Chief Marketing Officer)",
      "Taming Your Finances (role of Chief Financial Officer)",
      "Managing Your Firm (role of Chief Operating Officer)",
      "Cultivating Your Relationships (roles of Chief Public Relations Officer and Chief Sales Officer)",
      "Attaining Client Satisfaction (role of Chief Communications Officer)",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The role-based split of a practice — strategy, marketing, finance, operations, relationships, client communication — informed how AIJUR divides its firm-operations and business-development domains. Its treatment of the consultation as a tracked, converted event shaped our matter-intake skill.",
    kind: "operations",
  },
  {
    id: "src.small-firm-roadmap",
    title: "The Small Firm Roadmap Revisited: A Guide to the Healthy Law Firm of Your Future",
    author: "Stephanie Everett and Aaron Street",
    year: 2023,
    language: "en",
    publisher: "Lawyerist Media",
    domains: [
      "dom.firm-operations",
      "dom.client-relations",
      "dom.teamwork-leadership",
      "dom.self-management",
    ],
    sections: [
      "Part 1: How We Got Here — Lawyers Are Falling Behind; A Look Toward the Future; Rethinking Law as a Business; The Lawyerist Vision",
      "Part 2: The Small Firm Roadmap — Preparing for the Journey; Healthy Strategy; Healthy Team; Healthy Clients; Healthy Systems; Healthy Profits; Healthy Owners",
      "The Future of Law Is Yours",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Directly behind AIJUR's insistence that unanswered calls, unexplained delays and impenetrable drafting are the real client complaints — not lost cases. Its healthy-systems material shaped our workflow, file-organisation and quality-control skills.",
    kind: "operations",
  },
  {
    id: "src.modernize-your-law-firm",
    title: "Modernize Your Law Firm: Transform Your Law Firm for the Future",
    author: "Lynda Artesani",
    year: 2024,
    language: "en",
    publisher: "Business Expert Press",
    domains: ["dom.digital-ai", "dom.firm-operations"],
    sections: [
      "History of Law Firm Workflows",
      "Understanding the Automation Process",
      "Why Outdated Software Is Hurting Your Firm",
      "Data Security",
      "The Virtual Firm",
      "Identify Your Tech Stack",
      "Adjustments to Make in a Post-COVID World",
      "How to Adapt and Get Your Staff to Accept Technology",
      "Microsoft or Google?",
      "The Future: Legal Accounting and Blockchain",
      "Summary and Final Comments: Recommendations for a Modern Law Firm",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The practical basis for AIJUR's digital and AI domain: map the workflow before automating it, treat client data security as a professional obligation, and expect resistance from the team as a normal stage rather than a failure.",
    kind: "operations",
  },
  {
    id: "src.legal-ops-kpis",
    title: "Legal Operations KPIs: The Professional's Handbook to Operational Excellence",
    author: "Mori Kabiri",
    year: 2024,
    language: "en",
    publisher: "InfiniGlobe",
    domains: ["dom.firm-operations", "dom.professional-judgment", "dom.digital-ai"],
    sections: [
      "Part I: Definitions — From Data to Strategic Insights; data, metric, indicator, KRI, RI, KPI, PI and report; Legal Data Analytics Readiness Model; why and how we visualise data",
      "Part II: List of Metrics and Reports — Spend Management; Budgeting; matter, vendor, practice-area and cycle-time measures",
      "Part III: Best Practices",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Taught AIJUR the difference between a number a firm collects and a number a firm acts on. We used its logic — cycle time, budget variance, matter ageing — to define what measurable evidence a lawyer can offer for the quality-control and workflow skills.",
    kind: "operations",
  },
  {
    id: "src.fire-proof",
    title:
      "Fireproof: A Five-Step Model to Take Your Law Firm from Unpredictable to Wildly Profitable",
    author: "Mike Morse and John Nachazel",
    year: 2021,
    language: "en",
    publisher: "Lioncrest Publishing",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.business-development"],
    sections: [
      "Know Thyself",
      "Hiring, Firing, and Paying",
      "The Jumbotron Principle",
      "Run Your Business like You Run Your Biggest Case",
      "Cherry Garcia Beats Vanilla",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Source of AIJUR's view that a firm should apply to its own operations the rigour it applies to a major case file. Its scoreboard idea and its documented, repeatable intake procedure shaped our matter-intake and quality-control levels.",
    kind: "operations",
  },
  {
    id: "src.68-power-moves",
    title: "68 Power Moves to Build a Law Firm Clients Can't Ignore",
    author: "Neal Goldstein",
    year: 2024,
    language: "en",
    publisher: "Advantage Media",
    domains: ["dom.client-relations", "dom.business-development", "dom.self-management"],
    sections: [
      "Laying the Foundation — Establishing Genuine Connections",
      "Storytelling and Communication — Building Bonds Through Words",
      "Nurturing Relationships — Family, Friends, and the Community",
      "Mastering Your Time — Daily, Weekly, and Yearly Habits",
      "Investing in Personal Growth — Soft Skills and Mentorship",
      "The Power of Relationships — Building and Strengthening Networks",
      "Client-Centered Approach — Treating Clients Like Family",
      "Going Beyond — Unexpected Ways to Build Relationships",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "A catalogue of small, repeatable relationship behaviours — calling the client before they call you, naming the weaknesses of a case honestly, reviewing the calendar on a fixed rhythm. AIJUR took the principle that trust is built by many small kept promises, not one impressive performance.",
    kind: "professional",
  },
  {
    id: "src.four-thousand-weeks",
    title: "Four Thousand Weeks: Time Management for Mortals",
    author: "Oliver Burkeman",
    year: 2021,
    language: "en",
    publisher: "Farrar, Straus and Giroux",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "Part I: Choosing to Choose — The Limit-Embracing Life; The Efficiency Trap; Facing Finitude; Becoming a Better Procrastinator; The Watermelon Problem; The Intimate Interrupter",
      "Part II: Beyond Control — We Never Really Have Time; You Are Here; Rediscovering Rest; The Impatience Spiral; Staying on the Bus; The Loneliness of the Digital Nomad; Cosmic Insignificance Therapy; The Human Disease",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Underpins AIJUR's refusal to teach time management as fitting more in. We took the argument that capacity is fixed, so priority setting is an act of deliberate refusal, and that chasing total efficiency simply raises the volume of incoming work.",
    kind: "professional",
  },
  {
    id: "src.meditations-for-mortals",
    title:
      "Meditations for Mortals: Four Weeks to Embrace Your Limitations and Make Time for What Counts",
    author: "Oliver Burkeman",
    year: 2024,
    language: "en",
    publisher: "Farrar, Straus and Giroux",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "Week One: Being Finite — on the liberation of defeat; on actually doing things; on paying the price; against productivity debt; the art of reading and not reading; you can't care about everything; let the future be the future",
      "Week Two: Taking Action — decision-hunting; finish things; look for the life task; befriending what you fear; rules that serve life; three hours; develop a taste for problems",
      "Week Three: Letting Go — what if this were easy?; the reverse golden rule; don't stand in generosity's way",
      "Week Four: Showing Up",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Gave AIJUR the practice of finishing matters rather than accumulating open ones, and the done-list idea behind our reflection steps. It supports the resilience skill's stance that a lawyer never reaches a trouble-free phase and should stop waiting for one.",
    kind: "professional",
  },
  {
    id: "src.your-brain-at-work",
    title:
      "Your Brain at Work: Strategies for Overcoming Distraction, Regaining Focus, and Working Smarter All Day Long",
    author: "David Rock",
    year: 2020,
    language: "en",
    publisher: "Harper Business",
    domains: [
      "dom.self-management",
      "dom.teamwork-leadership",
      "dom.negotiation-influence",
      "dom.professional-judgment",
    ],
    sections: [
      "Act I: Problems and Decisions — The Morning Information Overwhelm; A Project That Hurts to Think About; Juggling Five Things at Once; Saying No to Distractions; Searching for the Zone of Peak Performance; Getting Past a Roadblock",
      "Act II: Stay Cool Under Pressure — Derailed by Drama; Drowning amid Uncertainty; When Expectations Get Out of Control",
      "Act III: Collaborate with Others — Turning Enemies into Friends; When Everything Seems Unfair; The Battle for Status",
      "Act IV: Facilitate Change — When Other People Lose the Plot; The Culture That Needs to Transform",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The cognitive science behind several AIJUR design rules: decide hard questions while fresh, name an emotion to reduce its grip, and treat status, certainty and fairness as live threats in any negotiation or feedback conversation. It also grounds our warning that unmanaged client expectations become emotional events, not information gaps.",
    kind: "professional",
  },
  {
    id: "src.the-antidote",
    title: "The Antidote: Happiness for People Who Can't Stand Positive Thinking",
    author: "Oliver Burkeman",
    year: 2012,
    language: "en",
    publisher: "Faber and Faber",
    domains: ["dom.self-management", "dom.professional-judgment"],
    sections: [
      "On Trying Too Hard to Be Happy",
      "What Would Seneca Do? The Stoic Art of Confronting the Worst-Case Scenario",
      "The Storm Before the Calm: A Buddhist Guide to Not Thinking Positively",
      "Goal Crazy: When Trying to Control the Future Doesn't Work",
      "Who's There? How to Get Over Your Self",
      "The Safety Catch: The Hidden Benefits of Insecurity",
      "The Museum of Failure: The Case for Embracing Your Errors",
      "Memento Mori: Death as a Way of Life",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Supports AIJUR's hardest professional rule: never promise an outcome. Naming the realistic worst case out loud calms a client more than reassurance does, and treating errors as reviewable material rather than shame is the basis of our quality-control and resilience skills.",
    kind: "professional",
  },
  {
    id: "src.introverted-leader",
    title: "The Introverted Leader: Building on Your Quiet Strength",
    author: "Jennifer B. Kahnweiler",
    year: 2018,
    language: "en",
    publisher: "Berrett-Koehler Publishers",
    domains: ["dom.teamwork-leadership", "dom.communication", "dom.business-development"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read for its 4 P's framework (preparation, presence, push, practice) and its diagnosis of four concrete failure modes — stress, perception gaps, career derailers, and invisibility — that quieter professionals face at work. We took from it the case that under-delegation is driven by nameable psychological resistance rather than a pure skills gap, a sharper behavioral definition of listening (\"attunement\", not just eye contact), concrete mechanics for running meetings that surface quieter input (written idea generation, separating brainstorming from decisions), and the concept of informal decision-making channels — \"the meeting before the meeting\" — as a distinct organizational-navigation skill. The book insists these are learnable techniques, not personality fixes, consistent with AIJUR's rule against inferring learner traits.",
    kind: "professional",
  },
  {
    id: "src.rainmaker",
    title: "How to Become a Rainmaker: The Rules for Getting and Keeping Customers and Clients",
    author: "Jeffrey J. Fox",
    year: 2000,
    language: "en",
    publisher: "Hyperion",
    domains: ["dom.business-development", "dom.client-relations", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read in substantial part (introduction, roughly 30 of 50 short chapters spanning early through late material, the dollarization methodology, a worked case study, and the epilogue). The book's real contribution to AIJUR is a blunt, transactional business-development playbook built around a small number of mechanical disciplines: translate every claimed benefit into an explicit dollar figure before presenting it, concentrate contact effort on the highest-potential prospects rather than spreading it evenly, end every substantive client interaction with an explicit ask for the next commitment rather than a passive presentation, and reframe objections as shared objectives phrased as questions. It also offers sharp, specific language tactics for overcoming refusal and treats the physical staging of client meetings as a controllable success variable. Useful for AIJUR's business-development domain, particularly value-quantification and targeting-discipline content not covered by the current skill set; less useful for client-relations tone, which trends more transactional/American-sales than AIJUR's relationship-centered register.",
    kind: "professional",
  },
  {
    id: "src.they-ask-you-answer",
    title: "They Ask, You Answer",
    author: "Marcus Sheridan",
    year: 2019,
    language: "en",
    publisher: "Wiley",
    domains: ["dom.business-development", "dom.communication", "dom.client-relations"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read for its core marketing philosophy: that trust in a skeptical buyer is built by proactively publishing honest answers to the five questions prospects research most — cost, weaknesses, comparisons, reputation, and \"who's actually best for this\" — rather than waiting to address them face-to-face. Its sharpest contributions for AIJUR are \"assignment selling\" (using short educational content as pre-meeting homework that measurably improves meeting quality and close rates), the \"disarmament\" move of naming one's own limits before making a comparative case, and a structural argument that trust-building content efforts collapse without a single named owner. Less a communication-skills book than a case for treating unprompted transparency — especially about price and weaknesses — as the mechanism of trust itself.",
    kind: "professional",
  },
  {
    id: "src.built-to-sell",
    title: "Built to Sell: Creating a Business That Can Thrive Without You",
    author: "John Warrillow",
    year: 2011,
    language: "en",
    publisher: "Portfolio",
    domains: ["dom.firm-operations", "dom.business-development", "dom.teamwork-leadership"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read in full for chapters covering specialization, sales-team design, cash-flow/billing mechanics, and the deal process. Its real contribution to AIJUR is more specific than \"documented process over memory\": it argues a service becomes valuable — and salable, staffable, and delegable — only once it is productized into a named, fixed-scope, fixed-price offering that any team member can execute, and that dependence on one person is something outside evaluators actively probe for and price down. We took from it the concrete mechanics behind AIJUR's delegation and knowledge-management skills, plus new material on recurring-engagement design and late-stage negotiation repricing pressure not previously covered.",
    kind: "operations",
  },
  {
    id: "src.purple-cow",
    title: "Purple Cow: Transform Your Business by Being Remarkable",
    author: "Seth Godin",
    year: 2003,
    language: "en",
    publisher: "Portfolio",
    domains: ["dom.business-development", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Purple Cow contributes the differentiation counterpart to AIJUR's client-experience material: where sources on service quality focus on how a lawyer handles the relationship, this one argues the underlying offering itself must be distinctive enough to be noticed and talked about, because a merely competent, interchangeable service is now invisible in a crowded market. We took from it the audience-segmentation logic (design for the minority who will notice and advocate, not the skeptical median client), the argument that blending in is riskier than standing out, and the caution that a single successful differentiator decays unless a firm keeps reinvesting in the next one. Note: the ingested file is a condensed third-party summary of the book (a \"Joosr\" digest, ~23 pages), not the full original text — its concepts are treated as reliable pointers to Godin's argument, not as a substitute for the complete work.",
    kind: "professional",
  },
  {
    id: "src.jab-jab-right-hook",
    title: "Jab, Jab, Jab, Right Hook: How to Tell Your Story in a Noisy Social World",
    author: "Gary Vaynerchuk",
    year: 2013,
    language: "en",
    publisher: "HarperBusiness",
    domains: ["dom.business-development", "dom.communication", "dom.digital-ai"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Read for its central discipline: earn the right to ask by giving real value first, calibrated to the register of the channel delivering it, while identity and substance stay constant across channels. We took from it the give-before-ask sequencing behind staying-top-of-mind, a transferable self-audit habit (\"would the recipient actually value this, or is it just for us?\"), and the effort-as-equalizer argument that disciplined preparation is a controllable competitive variable for small practices. Most of the book's actual content, however, is platform-specific social-media marketing mechanics — dated to 2013 platform norms and out of scope for this app's professional-skills and responsible-AI focus.",
    kind: "professional",
  },
  {
    id: "src.legal-project-management",
    title:
      "Legal Project Management: Critical Perspectives on a Managerial Practice Entering the Legal Profession",
    author: "Fiona Rogers, David Dombkins, and Felicity Bell",
    year: 2021,
    language: "en",
    publisher: "Law, Technology and Humans (peer-reviewed journal article)",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.client-relations"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Correction on ingestion: despite the source library's original title/author fields (which described Steven B. Levy's 2009 practitioner manual of the same catalogue title), the PDF actually held in the library and extracted is a 2021 peer-reviewed journal article by Rogers, Dombkins and Bell that studies legal project management critically, as a case of managerial practice entering the legal profession, rather than teaching it as a toolkit. Its value to AIJUR is conceptual rather than a source of reusable exercise formats: the empirical case that communication cadence, not technical error, drives most client complaints; the idea of making quality-cost-time trade-offs an explicit client choice rather than a silent compromise; and the warning that fragmenting matters into discrete tasks can create ethical blind spots and privilege risk on shared platforms. It anchors expectation-management and professional-judgment content conceptually.",
    kind: "operations",
  },
  {
    id: "src.governance-raci",
    title: "Governance & RACI Framework — دليل تحديد الأدوار والمسؤوليات",
    author: "AIJUR",
    year: 2025,
    language: "ar",
    publisher: "AIJUR Legal Operations & Governance System",
    domains: ["dom.firm-operations", "dom.teamwork-leadership", "dom.professional-judgment"],
    sections: [
      "الهدف (Purpose)",
      "تعريف RACI",
      "المبادئ الأساسية — مسؤول معتمد واحد فقط لكل عملية",
      "RACI للعمليات الأساسية: إدارة القضايا، اتخاذ القرار القانوني، الإدارة اليومية",
      "هيكل الحوكمة: المستوى الاستراتيجي، المستوى التشغيلي، المستوى الإداري",
      "ربط RACI مع النظام (AIJUR Integration)",
      "آلية التطبيق",
      "قواعد إلزامية",
      "النتيجة المتوقعة",
      "الاعتماد",
    ],
    usageRights: "owned",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "AIJUR's own governance document and the only Arabic-first source in the library. It supplies the rule our delegation and teamwork skills are built on: every matter and every decision has exactly one accountable owner recorded in the system, with responsibility, consultation and information assigned separately.",
    kind: "framework",
  },
  {
    id: "src.how-to-argue-and-win",
    title: "How to Argue and Win Every Time",
    author: "Gerry Spence",
    year: 1995,
    language: "en",
    publisher: "St. Martin's Press",
    domains: ["dom.negotiation-influence", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Full extraction confirms the book's real contribution is narrower than its title: persuasion is treated as a function of the arguer's visible authenticity — the alignment between what is said and how it is delivered — with disclosed uncertainty or self-interest often building more trust than projected confidence, and listening reframed as the active work of hearing the unmet need behind a counterpart's words or hostility rather than just their stated position. Its most transferable material beyond credibility and listening concerns how power imbalance (junior to senior, employee to institution) constrains what persuasion can accomplish, and how ongoing relationships call for identifying the real issue beneath a recurring dispute rather than winning the immediate exchange. Chapters on parenting, courtroom oratory technique, and corporate-ethics polemics fall outside this app's professional-skills scope and were not mined for exercise content.",
    kind: "advocacy",
  },
  {
    id: "src.making-your-case",
    title: "Making Your Case: The Art of Persuading Judges",
    author: "Antonin Scalia and Bryan A. Garner",
    year: 2008,
    language: "en",
    publisher: "Thomson/West",
    domains: ["dom.negotiation-influence", "dom.communication", "dom.legal-english"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "A close, numbered-principles treatment of judicial persuasion whose real value to this app lies less in its litigation mechanics and more in two transferable disciplines: calibrated confidence (never asserting more than one actually knows, volunteering weaknesses early rather than waiting to be caught) and composure under real-time questioning (answering directly before qualifying, never stalling, distinguishing hostile from merely blunt questions). Most useful for sharpening skill.avoiding-guarantees, skill.difficult-questions, skill.le-difficult-questions, and skill.plain-explanation; its statutory-interpretation and brief-mechanics chapters are litigation-specific and out of scope for this app.",
    kind: "advocacy",
  },
  {
    id: "src.tools-of-argument",
    title: "The Tools of Argument: How the Best Lawyers Think, Argue, and Win",
    author: "Joel P. Trachtman",
    year: 2013,
    language: "en",
    publisher: "CreateSpace",
    domains: ["dom.negotiation-influence", "dom.professional-judgment"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Offers a structured taxonomy of the recurring moves used to win legal arguments — contesting forum and jurisdiction, reframing what a dispute is really about, allocating the burden of proof, exploiting gaps in how a text is read, invoking or distinguishing precedent, and disputing the remedy — organized as a repeatable pattern of claim and counter-claim that maps naturally onto anticipating an opposing party's next move. Its lasting value to this app is as transferable argument scaffolding for negotiation, persuasion, and pressure-tactic training, and as a sharp vocabulary (procedural versus substantive justice) for explaining to clients why a legally correct outcome can still feel unfair, rather than as a source of jurisdiction-specific legal doctrine. Concepts adapted, in original wording, for skill.persuasive-argument, skill.reading-the-counterpart, skill.handling-pressure-tactics, and skill.professional-ethics.",
    kind: "advocacy",
  },
  {
    id: "src.thinking-like-a-lawyer",
    title: "Thinking Like a Lawyer: A New Introduction to Legal Reasoning",
    author: "Frederick Schauer",
    year: 2009,
    language: "en",
    publisher: "Harvard University Press",
    domains: ["dom.professional-judgment", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Schauer's real argument is that legal reasoning is ordinary human reasoning disproportionately organized around devices — rule-following, precedent, deference to authority, burdens of proof — that deliberately produce outcomes different from an all-things-considered judgment, in the service of predictability and institutional stability rather than case-specific fairness. Its most usable material for this app is the rules-versus-standards distinction and the treatment of burdens of proof as calibrated, intentional tolerance for particular kinds of error, both of which ground scenarios in skill.plain-explanation, skill.avoiding-guarantees and skill.expectation-management about explaining legal uncertainty honestly rather than generically. Large stretches of the book (precedent doctrine, canons of statutory construction, jurisdiction and deference) remain academic background rather than skills-training source material.",
    kind: "advocacy",
  },
  {
    id: "src.legal-analyst",
    title: "The Legal Analyst: A Toolkit for Thinking about the Law",
    author: "Ward Farnsworth",
    year: 2007,
    language: "en",
    publisher: "University of Chicago Press",
    domains: ["dom.professional-judgment", "dom.negotiation-influence"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Farnsworth's synthesis of the analytical tools economists, game theorists, and psychologists have brought into legal reasoning gives this app concrete, well-evidenced material for advisory (non-litigation) practice: forward-looking incentive analysis as a counterweight to backward-looking fairness judgments, heuristics for allocating risk to whichever party can bear or prevent it most cheaply, and the principal-agent logic behind fee structures and monitoring in the lawyer-client relationship. Its treatment of decision-distorting biases — hindsight and outcome bias, loss-versus-gain framing effects, anchoring, and self-serving overconfidence — offers directly teachable failure modes for how lawyers and clients misjudge risk and past decisions. The book's more purely doctrinal and mathematical material (voting theory, Bayesian probability mechanics, admiralty and damages case law) is less relevant to this app's mandate and was set aside.",
    kind: "advocacy",
  },
  {
    id: "src.maccarthy-cross-exam",
    title: "MacCarthy on Cross-Examination",
    author: "Terence F. MacCarthy",
    year: 2007,
    language: "en",
    publisher: "American Bar Association",
    domains: ["dom.negotiation-influence", "dom.communication"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Extraction confirmed the book's real discipline: cross-examination works by pairing short, declarative statements with a brisk pace and no tolerance for silence, so the questioner rather than the witness owns the narrative and the witness is held to one-word confirmations — the opposite of what a client interview needs. AIJUR draws from it a sharpened version of a principle skill.questioning already gestures at: question length and phrasing are a deliberate lever, and where cross-examination shortens, closes and speeds up to seize narrative control, client interviewing lengthens, opens and slows down to hand narrative control to the client. Its impeachment tactics, courtroom misdirection and adversarial-ethics discussion have no client-facing analog and are excluded from the content set.",
    kind: "advocacy",
  },
  {
    id: "src.rule-of-law",
    title: "The Rule of Law",
    author: "Tom Bingham",
    year: 2010,
    language: "en",
    publisher: "Allen Lane",
    domains: ["dom.professional-judgment"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Bingham's account of the rule of law as a set of interlocking principles — accessible and prospective law, decisions governed by rule rather than unchecked discretion, equality before the law, lawful and rational use of public power, protection of fundamental rights, dispute resolution without prohibitive cost or delay, a fair hearing, and a state's own compliance with the law it invokes against others — gives professional-ethics its clearest grounding for why a lawyer's duty runs to the legal system, not only to the immediate client. Its most usable material is the fair-trial chapter's treatment of candour toward the tribunal and genuine equality of arms, together with its case studies of officials and lawyers constructing technically defensible justifications for outcomes the law did not actually permit — a pattern directly adaptable into professional-ethics and avoiding-guarantees scenarios. Large parts of the book (constitutional history, international-law analysis, the parliamentary-sovereignty debate) are jurisprudence rather than practice-ready material and remain background context.",
    kind: "professional",
  },
  {
    id: "src.ultimate-associate-marketing",
    title: "The Ultimate Law Firm Associate's Marketing Checklist",
    author: "Ross Fishman",
    year: 2019,
    language: "en",
    publisher: "Fishman Marketing",
    domains: ["dom.business-development", "dom.self-management"],
    sections: [
      "Introduction — why associates avoid business development",
      "A year-by-year checklist from first-year to senior associate",
      "Internal visibility and relationships inside the firm",
      "Writing, speaking and article placement",
      "Social media and professional networks",
      "Building and maintaining a contact list",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Confirmed for AIJUR that business development is a staged competency with different expectations at each year of practice, not a partner-only activity. Its year-by-year structure informed how our business-development and relationship-building levels rise.",
    kind: "professional",
  },
  {
    id: "src.ali-rise",
    title: "All Rise: Practical Tools for Building High-Performance Legal Teams",
    author: "Benjamin Sachs",
    year: 2024,
    language: "en",
    publisher: "American Bar Association",
    domains: [
      "dom.teamwork-leadership",
      "dom.self-management",
      "dom.communication",
      "dom.firm-operations",
    ],
    sections: [
      "Part 1: Trust — Psychological Safety; The Fundamental Attribution Error; Working Style Differences; Trust Building Without Trust Falls",
      "Part 2: Ownership — The Broken Venn Diagram; Managing Up; Managing Down; Cultivating Ownership",
      "Part 3: Productive Conflict — Iron Sharpens Iron; Conflict Styles; Emotional Obstacles; Breaking Stalemates",
      "Part 4: Accountability — Going Supersonic; Project Management; Autonomy; Creating a Culture of Continuous Feedback; Evaluating High-Performance Legal Teams",
      "Appendices: Team Building Program Template; Team Health Assessment Survey Template",
    ],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "The richest single source for AIJUR's teamwork and leadership domain: psychological safety as the precondition for a junior raising a problem early, managing up as a named skill, and feedback as a continuous habit rather than an annual event. Its project-management and autonomy material shaped our delegation levels.",
    kind: "professional",
  },

  // ---------------------------------------------------------------------
  // Narrative works. These inform AIJUR through illustrative texture and
  // professional-conduct themes -- moral courage, case-acceptance judgment,
  // the cost of an unresolved matter, the line between coaching a witness
  // and educating a client -- never through frameworks or checklists the
  // way the professional/operations sources above do. Historical/doctrinal
  // specifics (a novel's setting, a era's procedure) are not reusable
  // training content; only the underlying professional pattern is. As with
  // every other source, no scene, passage or dialogue is reproduced --
  // themes only, in AIJUR's own words.
  // ---------------------------------------------------------------------
  {
    id: "src.to-kill-a-mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    language: "en",
    publisher: "J. B. Lippincott & Co.",
    domains: ["dom.professional-judgment", "dom.communication", "dom.self-management"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library as the reference case for the cost of professional integrity when a lawyer takes on an unpopular but correct position: a small-town defense lawyer represents an unjustly accused client against his own community's hostility, examines witnesses with patient fairness rather than aggression even while opposing counsel does the opposite, and absorbs public insult without retaliating because de-escalation serves the matter better than being right in the moment. Used for scenario texture and hook material on moral courage, composure under social pressure, and how to explain a losing case honestly to people who trust you -- not for competency extraction, since it contains no frameworks or techniques to mine, and its historical racial-injustice setting is not itself reusable training content.",
    kind: "narrative",
  },
  {
    id: "src.a-civil-action",
    title: "A Civil Action",
    author: "Jonathan Harr",
    year: 1995,
    language: "en",
    publisher: "Random House",
    domains: ["dom.professional-judgment", "dom.self-management", "dom.firm-operations"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library as a documented account of what happens when a firm's ambition for one case outgrows what the firm can actually sustain: a plaintiffs' lawyer's early high-risk win teaches him the wrong lesson, and he carries that overconfidence into a matter that eventually costs him his firm's solvency, his home, and a long relationship, before a credible, unglamorous rebuilding period years later. Its value to AIJUR is not the toxic-tort law, which is jurisdiction-specific and dated, but the documented decision points -- the case-acceptance judgment, the discovery lapse never escalated, the expert-witness theory commissioned before it was tested, the refusal to recalibrate once a judge turned hostile -- that make concrete what workload boundaries, evidentiary honesty, and professional resilience look like when they fail and when they eventually recover.",
    kind: "narrative",
  },
  {
    id: "src.anatomy-of-a-murder",
    title: "Anatomy of a Murder",
    author: "Robert Traver",
    year: 1958,
    language: "en",
    publisher: "St. Martin's Press",
    domains: ["dom.professional-judgment", "dom.communication", "dom.client-relations"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library as fiction's sharpest treatment of a line AIJUR teaches directly: where client education ends and coaching a story begins. A former-prosecutor lawyer-narrator walks his client through every legal category of defense before asking what happened, then privately questions how much that sequencing shaped the account he got back -- and later gives a witness instructions that coach demeanor and process, never content. Read for its client-interview and witness-preparation mechanics and its courtroom examination discipline, not for the U.S. criminal procedure and 1950s Michigan setting that surround them, which this platform does not teach.",
    kind: "narrative",
  },
  {
    id: "src.bleak-house",
    title: "Bleak House",
    author: "Charles Dickens",
    year: 1853,
    language: "en",
    publisher: "Bradbury and Evans",
    domains: ["dom.client-relations", "dom.professional-judgment", "dom.firm-operations"],
    usageRights: "public_domain",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library as the canonical portrait of a matter that never closes: a case whose costs exist to justify its own continuation, decided at last only because the estate it was fought over has been entirely consumed by the fighting. We drew from it the case that being busy on a file is not the same as moving it toward an end, that a professional owes a client a real, timely answer about when to stop rather than managed hope, and that a matter with no designed endpoint will, left alone, design one for itself -- usually at the client's expense.",
    kind: "narrative",
  },
  {
    id: "src.the-innocent-man",
    title: "The Innocent Man: Murder and Injustice in a Small Town",
    author: "John Grisham",
    year: 2006,
    language: "en",
    publisher: "Doubleday",
    domains: ["dom.professional-judgment", "dom.client-relations", "dom.digital-ai"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library as the one narrative source built entirely from documented fact rather than invention: a real wrongful conviction in which coerced confessions, an unreliable jailhouse informant, forensic testimony that overstated what its methods could show, and a defense that skipped foundational procedural steps compounded across multiple professionals rather than any single actor's failure. We draw from it not the US capital-procedure specifics, which don't transfer, but the pattern itself -- how a working theory hardens into unexamined certainty as it passes from investigator to prosecutor to expert to defense counsel to judge, and what baseline diligence (testing an expert's claim, raising a known competency issue, disclosing what you already hold) would have interrupted it at any one point. Handled here as a case study in professional judgment under pressure, not as entertainment.",
    kind: "narrative",
  },
  {
    id: "src.ultimate-punishment",
    title: "Ultimate Punishment: A Lawyer's Reflections on Dealing with the Death Penalty",
    author: "Scott Turow",
    year: 2003,
    language: "en",
    publisher: "Farrar, Straus and Giroux",
    domains: ["dom.professional-judgment", "dom.communication", "dom.self-management"],
    usageRights: "reference_only",
    analysisStatus: "extracted",
    reviewStatus: "ai_suggested",
    notes:
      "Kept in the library for a single reason: it is a rare first-person, verifiable account of a lawyer publicly reversing a long-held professional position under the weight of accumulated case evidence, not a single dramatic reveal. We draw on it for the discipline of separating a personal vote from an institutional recommendation, the method of testing an intuition against a body of case files rather than resting on one memorable example, and the rhetorical structure of arguing an unpopular reversed position -- concede the strongest counter-argument, show the evidence trail, be honest about what still troubles you. The book's subject matter, US capital punishment policy, is out of scope for this app and is not the reason it is here.",
    kind: "narrative",
  },
];
